### ISSUE TITLE
LibertyMod | To-do

### ISSUE THREAD

**Issue by LordAttano** [LordAttano/LibertyMod#1]
Base features:
* [ ]  Login system with accounts.
* [ ]  Admin system structure.
* [ ]  Improved duel system.
* [ ]  Function to handle centerprints more efficiently, such as MOTD, news, etc.

Commands/Features:
* [ ]  Basic management tools (Kick, ban, etc.)
* [ ]  Team management tools (Lock/unlock teams, shuffle teams, force team change, etc.)
* [ ]  Dynamic universal word triggers (For teleports and other things).
* [ ]  Modern emote system (Walkable emotes, non-frozen).
* [ ]  Chat protection.
* [ ]  Stats (tracking and end-result stats on match end).
* [ ]  Map modding tools (Shader remapping, add models, effects, etc.)

New modes:
* [ ]  InstaGib
* [ ]  Last Man Standing (With option to play some of the other modes as LMS as well).
- More to be decided.
