### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by LordAttano** [LordAttano/LibertyMod#1]
Base features:
* [ ]  Easily adjustable mod name and colours.
* [ ]  Login system with accounts.
* [ ]  Admin system structure (text based).
* [ ]  Improved duel system.
* [ ]  Function to handle centerprints more efficiently, such as MOTD, news, etc.
* [ ]  Tag protection.
* [ ]  New way of handling names and colours.
* [ ]  Multi name check

Commands/Features:
* [ ]  Basic management tools (Kick, ban, etc.)
* [ ]  Team management tools (Lock/unlock teams, shuffle teams, force team change, etc.)
* [ ]  Dynamic universal word triggers (For teleports and other things, with commands to change these easily in-game).
* [ ]  Modern emote system (Walkable emotes, non-frozen).
* [ ]  Chat protection.
* [ ]  Stats (tracking and end-result stats on match end).
* [ ]  Map modding tools (Shader remapping, add models, effects, etc.)
* [ ]  Client commands (info, etc.)
* [ ]  Admin management (Adjust accounts from in-game).

New modes:
* [ ]  InstaGib
* [ ]  Kill Quota
* [ ]  Last Man Standing (With option to play some of the other modes as LMS as well).
- More to be decided.
