### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by LordAttano** [LordAttano/LibertyMod#1]
Basic:
* [ ]  Account based login system.
* [ ]  Base admin system structure.
* [ ]  Easily adjustable mod name, colours, and symbols.
* [ ]  Duel system.
* [ ]  Name system with updated checks for colours and blank names.
* [ ]  Duplicate name check.
* [ ]  Function to efficiently handle centerprint messages.

Commands/Features:
* [ ]  Basic tools (kick, ban, etc.)
* [ ]  Team management tools (lockteam, shuffleteam, etc.)
* [ ]  Client commands (info, etc.)
* [ ]  Emotes (Walkable, etc.)
* [ ]  Chat protection.
* [ ]  Map modding.
* [ ]  Word trigger system (for teleports and such).

New modes:
* [ ]  InstaGib.
* [ ]  Kill Quota.
* [ ]  Red Rover.
* [ ]  Last Man Standing.
* [ ]  More to be decided.
